[paths]
working_directory = "./models"

[view.scene]
background_color = [0.1, 0.1, 0.12]  # Night grey
line_thickness = 2

[view.camera]
pan_speed = 10.0
rotate_speed = 100.0
animation_duration = 0.5
show_marker_at_start = false
