[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "gmsh>=4.15.0",
    "ipython>=9.10.0",
    "nurbslib",
    "panda3d>=1.10.16",
]

[tool.uv]
package = true

# FIXME: will be change, using a path like this isn't good
# NOTE For find nurbslib in the folder wheel, you can run "uv sync --find-links wheel"
# [tool.uv.sources]
# nurbslib = { path = "../vtk_converter/nurbslib", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pdoc>=16.0.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report=html --cov-report=term"
testpaths = ["tests"]


