name: Documentation

on:
  push:
    branches: [main]
  workflow_dispatch: # Permet de lancer la doc manuellement pour tester

# Empêche d'avoir plusieurs déploiements en même temps
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # for gmsh and panda3D
      - name: Install system graphics dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa libgl1-mesa-dev libosmesa6 

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --dev

      - name: Build Docs with pdoc
        run: uv run pdoc ./bot -o ./docs_out --docformat google

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs_out' # On utilise un nom de dossier bien distinct

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
